# Generated by Django 4.2.6 on 2023-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('nouns', models.TextField()),
                ('adjectives', models.TextField()),
                ('verbs', models.TextField()),
            ],
        ),
    ]
